customer_name: test17
odoo_version: '17.0'
customer_shortname: test17
repo_name: test17_kerp
project_id: '0000'
project_name: test17_kerp
odoo_company_name: test17
odoo_main_lang: fr_FR
odoo_aux_langs: 
